services:
  portainer:
    image: portainer/portainer-ce
    container_name: toolbox_container_test
    ports:
      - "9001:9001"
      - "8001:8001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data    # This is crucial for storing compose files
    restart: always

volumes:
  portainer_data: